---
apiVersion: v1
kind: Service
metadata:
  namespace: jnc
  name: jnc-redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      name: jnc-redis
      targetPort: 6379
      nodePort: 30279
  selector:
    name: jnc-redis

