apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysqldata
      annotations:
          volume.beta.kubernetes.io/storage-class: "devops-k8s-nfs"
    spec:
      accessModes:
          - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
