apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-node-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:192.168.59.201
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:192.168.59.202
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:192.168.59.203
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:192.168.59.204
      