---
apiVersion: v1
kind: Service
metadata: 
  name: nodejs-1
  namespace: jenkins
  annotations:
spec: 
  type: NodePort
  selector: 
    name: nodejs-1
  ports: 
    - name: ssh-port
      port: 22
      nodePort: 32004
      targetPort: 22
      protocol: TCP  