kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-master-pvc
  namespace: jenkins
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cscdevops-nfs
  resources:
    requests:
      storage: 10Gi 
