apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12-dev
        env:
        resources:
          limits:
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: jounald
          mountPath: /run/systemd/journal/
          readOnly: true
        - name: fluentbit-conf
          mountPath: /fluent-bit/etc/
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: jounald
        hostPath:
          path:  /run/systemd/journal/
      - name: fluentbit-conf
        configMap:
          name: fluentbit-conf