---
apiVersion: v1
kind: Service
metadata: 
  name: ems-hana-proxyjdk7
  namespace: ems
  annotations:
spec: 
  type: NodePort
  selector: 
    name: ems-hana-proxy
  ports: 
    - name: dev-port
      port: 30015
      nodePort: 30015
      targetPort: 30015
      protocol: TCP  
    - name: test-port
      port: 30115
      nodePort: 30115
      targetPort: 30115
      protocol: TCP        
    - name: usdemo1-port
      port: 30215
      nodePort: 30215
      targetPort: 30215
      protocol: TCP      
    - name: perf-port
      port: 30315
      nodePort: 30315
      targetPort: 30315
      protocol: TCP             