apiVersion: v1
kind: Service
metadata: 
  name: tomcat
  namespace: tomcat
spec: 
  type: ClusterIP
  selector: 
    name: tomcat
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
