apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-proxy
  labels:
    k8s-app: kube-proxy
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: gcr.io/google_containers/kube-proxy:v1.7.1
        command:
        - sh
        - -c
        - /usr/local/bin/kube-proxy --kubeconfig=/srv/kubernetes/kube-proxy.kubeconfig
          --cluster-cidr=192.188.0.0/16
          --v=5 
        securityContext:
          privileged: true
        volumeMounts:
        - name: kubeconf
          mountPath: /srv/kubernetes
          readOnly: true
      volumes:
      - name: kubeconf
        configMap:
          name: kube-proxy.kubeconfig
