apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: redis

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: redis-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-reader-binding
subjects:
- kind: ServiceAccount
  name: redis-sa
  namespace: redis
roleRef:
  kind: ClusterRole
  name: redis-reader
  apiGroup: rbac.authorization.k8s.io
