---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-master
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis-master
      targetPort: 6379
      nodePort: 30379
  selector:
    name: redis

