# Full read access to the api and resources
#cluster-reader: Since every account that we have defined needs to be able to read the Kubernetes API, 
#we've created a role that we call cluster-reader. It has the ability to get, list, and watch any resource. 
#It also has access to all non-resource URLs (the API version endpoint, for example):
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
    nonResourceURLs: ["*"]
