#cluster-writer: This role gives its members full cluster access. 
#It is probably not strictly necessary for anything other than the clusters superadmins, 
#but we have added the kubelet as well
# Wide open access to the cluster (mostly for kubelet)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-writer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: ["*"]


