apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler:v1.10.0
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-scheduler --kubeconfig=/var/lib/kubernetes/kubeconfig/kube-scheduler.kubeconfig
      --v=5 --leader-elect=true 
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /var/log/
      name: logfile
    - name: localtime
      mountPath: /etc/localtime       
    - mountPath: /var/lib/kubernetes/kubeconfig/
      name: kubeconfig      
    - mountPath: /var/lib/kubernetes/certs/
      name: certs
      readOnly: true        
  volumes:
  - hostPath:
      path: /var/log/
    name: logfile
  - name: localtime
    hostPath:
      path: /etc/localtime  
  - hostPath:
      path: /var/lib/kubernetes/kubeconfig/
    name: kubeconfig
  - hostPath:
      path: /var/lib/kubernetes/certs/
    name: certs    