apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-exporter
  namespace: mongo-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-exporter
      annotations:
        prometheus.io/port: '9001'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'  
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mongo-exporter
      containers:
      - name: mongo-exporter
        image: registry.gcsc.sap.corp/mongodb/mongodb_exporter:v1.0.1
        imagePullPolicy: IfNotPresent
        args:
        - -mongodb.uri
        - "mongodb://monitor:monitor@${POD_IP}:27017"
        - -web.listen-address
        - ":9001"
        - -v
        - "10"
        resources:
          limits:
            memory: 100Mi     
        ports:
        - name: mon-port
          containerPort: 9001
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP