apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-jdk7-conf-devops
  namespace: jenkins
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZwakNDQTQ0Q0NRREt5SFlkUzJGMzVUQU5CZ2txaGtpRzl3MEJBUXNGQURDQmxERUxNQWtHQTFVRUJoTUMKUTA0eEN6QUpCZ05WQkFnTUFsTklNUXN3Q1FZRFZRUUhEQUpUU0RFTU1Bb0dBMVVFQ2d3RFUwRlFNUXd3Q2dZRApWUVFMREFORFUwTXhFVEFQQmdOVkJBTU1DRU5FUkVWV1QxQlRNVHd3T2dZSktvWklodmNOQVFrQkZpMUVURjgxCk4wSkJOamc0TURWR09UbENOekV3UmpZd01EQXdNVUZBWlhoamFHRnVaMlV1YzJGd0xtTnZjbkF3SGhjTk1UY3cKTnpFM01EY3dOakF5V2hjTk5EUXhNakF5TURjd05qQXlXakNCbERFTE1Ba0dBMVVFQmhNQ1EwNHhDekFKQmdOVgpCQWdNQWxOSU1Rc3dDUVlEVlFRSERBSlRTREVNTUFvR0ExVUVDZ3dEVTBGUU1Rd3dDZ1lEVlFRTERBTkRVME14CkVUQVBCZ05WQkFNTUNFTkVSRVZXVDFCVE1Ud3dPZ1lKS29aSWh2Y05BUWtCRmkxRVRGODFOMEpCTmpnNE1EVkcKT1RsQ056RXdSall3TURBd01VRkFaWGhqYUdGdVoyVXVjMkZ3TG1OdmNuQXdnZ0lpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRRHB1VmNtZ21NK0wyQWlXMWhORERvUlM0a3MydVpsM1lDNkJldmRndlFlCkdld0NOa2hoSTZ3UEphdzZka0daamxkbUxHN2ZRT2R6TGYyc1BpS3U3VnhrMmoxb3ArZDRjc0crYnluNDNXYWQKSFBkTE00OXJZNTRYeExySWtPVnIwdWNRVEVFYkFkMkVrcjBYcFQxdmRiSzdBbWdEL0ZPM3h0Ujl1aWxXRVo5VApGaUtLTVQ4bDcxZG9BT3FLQ1o1UTcrQ1NBMHY5WVFpTlRzaHJxUFR2UkJBaU5PYkVMWE5OM3JOTDdMTjFibkZOCjJaNnB0Q1UvWXh4OHBpQTRoVjJTUC9FWGlEK2lLb3lISzZYenRwcy90OExoeElBYWUxOXN3a2hNSWwwVWUrdVUKNkhoVW0ybkQ3b0Q3YTlQUVdhaGtKcExGcWFSMWYrUDIzbmhaUmNOT1ZOMWVacmxsVmN4VlNRNzhMM2VScXQ4cApYbTZkVjYzNkRHczJ4T2hZTVlvb3JrQ28wWEVOTzl0WWgxS1U5OG03QmtWL3BDVVNtN1YwUGppc2xVcDNLV1o2ClU3T2V2bU9KODgwZmNpYXlybmNLM1NtZmdyNWREUnE0VGU2SFlIdXg3bkg4a0xyVjBTQndiMXcwOFEwU1J5UmcKUFFhVHgyMit5Z2hEdWZ1TUorSEIvWFFCT1ZVU0djZEVYNGwxc2RvMm11Nm1zdFpIbFM1QUpkelNFbmpPTUFJNgplSkFucUF2VnlnRDJLSVJpaElTM2daTVpsN1RjUStWL2hoQUpJN2FISVcwUmRkWmJOZDNPUFd5OWthTEdwVm16CnJ0UzM1MThGSVF1SE5vWW8yblZzb20xMlBya3VZY3N4ajZWNXhmc2pabkhhTnkvS3E5UW9PbDRpMlBaOVhhVDAKMHdJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUIwNkc0dzJoTnlIYmgvT0NQNU5iME12TmtCZG52awpxMWx0QVJkNERPY05EemhTZmo1ay9LdnpvMldlbnFaT2RzdS9Sb3BxYWRmZ0NZWVhGNU9IRjFWdHdaaU4zZENnCmJDWHN5aWtKVU9OdkV2QTJhYXNWNmk0WVhzRnR3KzNNZVByMDNXTkpyMStBZWJKNmpkL0xCbndvTlBOS25iWS8KYWREa2FFQnphQUVFQVAraGt0TGxkUlgvb25wbTFGRjFiYXBtTVQydmx5TENNUUNxUzVXRDN3WkNuQXJ1WnpkTwpIUWpSbTBzWk56aGlXelpadnFscGdmZlFMODN1VFpUdWtIVU9uVXBMVXY3bG4zZFR4eG9QRnhjamhzSkZvMURnCktEeE9HKy9Rd2FRdDZoNDNlWFloUUpzSDRhWVh0ajd4L1BEWlN1cy9weXVLYnRpalJRN0pFb2Y0SFh6WlNQN0QKTnFiKzNoZkZ5OVVQWFFtL0FUZWF4bUNobmdoTitBUE1SeldwS3pYMGxRQUdHTGVMd1ZDdHBuNEswbUJPR09ZYgpjT0tNczBtcGRnejRKOGZUZ0FvNWxBMXdDWHpaSHh6UjJOZ2JEd05BQXZoNk1PcFZJa1VaS1VwbERSaFpwa1pnCmU2RkdJa2pZWllXbklCN0xRZkpQaUdoSUNOQ3h1V2NmR29WNG1hVWJua1ZFcXhGTVNXQU9ubDFBWENaZEFpRnEKc2xHc3g3bWlYTy9LQ2dZcFQ5cXU2dUNoUVdDZFpRNit2eFJLMEs5QXMwMmttcnZGQXQwQkxoU1FGVzNoZ1pERwoyQzlZbW5lemgxekF5ODZKZG5oODRpMys1Lzg2R2JEc2hFZUkrdmE3RzBBNWV1L0g5aTM4ZHU1R3JpNXRiZnlBCjk1aHBvaDVIUkNDNC93PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://10.58.137.243:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        namespace: jenkins
        user: cluster-admin
      name: cluster-admin@kubernetes
    current-context: cluster-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: cluster-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZLakNDQXhJQ0NRRGV3U0lKd0xubDhEQU5CZ2txaGtpRzl3MEJBUXNGQURDQmxERUxNQWtHQTFVRUJoTUMKUTA0eEN6QUpCZ05WQkFnTUFsTklNUXN3Q1FZRFZRUUhEQUpUU0RFTU1Bb0dBMVVFQ2d3RFUwRlFNUXd3Q2dZRApWUVFMREFORFUwTXhFVEFQQmdOVkJBTU1DRU5FUkVWV1QxQlRNVHd3T2dZSktvWklodmNOQVFrQkZpMUVURjgxCk4wSkJOamc0TURWR09UbENOekV3UmpZd01EQXdNVUZBWlhoamFHRnVaMlV1YzJGd0xtTnZjbkF3SGhjTk1UY3cKTnpJd01ETXdNelUxV2hjTk1qY3dOekU0TURNd016VTFXakFaTVJjd0ZRWURWUVFLREE1emVYTjBaVzA2YldGegpkR1Z5Y3pDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBT2pPSXlncHROa0NNdlpKCllROTJLQVN5S1o3N1kzeTA1Wi8yVjJFYnFkVEhYZnFMTHhkbDY4YVdnaDNFY090MmRzRWUzdW9jY25pMzZsbmMKSFQwQ2cycnBpNjBWY0s3UWxhMXpOaVBuT2s5TE5KQURjT09NMEozY0Ixb3RPcUl1T1Y0WlAxaGFRcTc3ZkpGSwo4bUloTnU0endQTTNDdFVTVzdmWTE1V01uQjExUWd6azg3NkRvNXg2Y2h1RFdDQ1ZCeHNRUjBia1hMWDdMS1J5CmlHRnpMYnA5VFR4Q1BCTjJjRjJFV1BvWjFwSGwvbktPb2xiY0lIN3lsV1VWdm1aUFlkZ2ZSQkJwRXVhMWNEbTQKQmZQNkdjRnZ5bHFlY3VERW50ZWEzSml2OFFQRTkrQ2tBK2RsVGd3MXhqVzFDdlFudEt6ckIyaDI3VkRWSitUawptOGR0UDFMdW4zNm9zTUtWbFgrZFl1Zzc1OXJlM2llY3F0QlJUeTlTdlpKOUgvem11QTNFaFpBOGV2cTZkOFN5ClNlRFJQdFlJL3R4dUJyN2Z4dDE5R1dSMFpGTGkyL2VOemZKbVloSXhpdDRYN201VUZTd0VzMFVUSElEZyt6VzQKU1l2Q2xTU0xoR0orWFJDU1lEQysrcmNMYVpLUG9MaGNiZmtId2xualoyQklRYVNNdytjeG9SVDROM2JWc0FZcQp2NlFqYkJNQ0xuUTMxRUo0YkJacXFMNjlOMEFMeVFxL1F1VVVvQTd0dUUzRU1HaWhqeHE5TzlCV0RhKzBGcUNSCnpzYUVvY1k1ZXJ5VVY4U1JKKzFEWmN5MTF5RmNNRlZ2RHVQajNkMUFDN1pNdVVYY3N0dTB0c0M4ZThuUmJuTW0KMlJmajk1akpKV1NzQVJUTWEvQlFBTmxwSXJFTEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUlIRQpMOFlOSzR2QWwvR2doL2ZNaEl5S29wdDVrbHBlbFMzTXFUSzRuZFJLMzdtRWV6T3F2WDM4S3FmUHdQbEQrK2F0CnpNakRYZ0xNNlQydmcyZ0NxbkwxRG04c3N5ek4wVzNvb0ExTXNCNHBKSVZwaWJrZ0tYblRMQWxXRDlrN3JLOVYKWHRoTEZONTJKcHVUZkgxV0U5cUJEYk51M05URFZTOHkveUdvOU4wQmNWenZIWms5UXViQzlQOUtkNHFyWGNscwpOTGpYM0FuYURKalE0M3phSHZ5QnpENzRkTUVIVzBraTdDQlRCVE9qK2t4N1VDRWhNNEhLTEYyQXE5eEo1L2cxCmg1Qlo2RGdmbU80blZHSXJ5ZHNsVVppeWNqaGU0SXJSMUFudEZaY09EZHg0cDM0bXl5UDIwSWNwM05LMzVuWVoKTW1aL0g4T0VnRjhvVFdkMnFlQXVmVkFXb3Z5S1ZLNU5QQ1FjUkgyM2p5eFhBaGcrQlJBUU5xNldMRTlaVWswOQpvMzJWZjlSMzc1R2N1dHVTRFVRN0Z5MXBib0JldjdIRGwwams4dUxTQjAvcEd6dUx5cUEvVWErS01DSUxGT0tuCktPTW9TOE14TTFVZTJ5bnlhS1FtZndlaGZoODNQeFZxZWx1RWI4YW9JUGNzR3U4NnZaSHRLM2QvZnp0Q1Jpa3IKTHcrSmFoOW9FcHdialoxMWxwQjN0NzhEUXo1M25zSTJPMTV3Yld3U1dDY2k4eXg4enhEN0dIVjFUZjg4Tldsbwp1TDNwSDZmY1RESnRqTzNUMG1xOVhYMmFzV2xNb0YwUzdBTTAzWEl3bDJoSnFRVG44cDc5d0dZM08zTndUaTY1CnlYNFNMc2g2YUFVR1ZUOWoyd2NQZ1FQajJ3a3FjS3E1UVZQckVPWFQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBNk00aktDbTAyUUl5OWtsaEQzWW9CTElwbnZ0amZMVGxuL1pYWVJ1cDFNZGQrb3N2CkYyWHJ4cGFDSGNSdzYzWjJ3UjdlNmh4eWVMZnFXZHdkUFFLRGF1bUxyUlZ3cnRDVnJYTTJJK2M2VDBzMGtBTncKNDR6UW5kd0hXaTA2b2k0NVhoay9XRnBDcnZ0OGtVcnlZaUUyN2pQQTh6Y0sxUkpidDlqWGxZeWNIWFZDRE9Uegp2b09qbkhweUc0TllJSlVIR3hCSFJ1UmN0ZnNzcEhLSVlYTXR1bjFOUEVJOEUzWndYWVJZK2huV2tlWCtjbzZpClZ0d2dmdktWWlJXK1prOWgyQjlFRUdrUzVyVndPYmdGOC9vWndXL0tXcDV5NE1TZTE1cmNtSy94QThUMzRLUUQKNTJWT0REWEdOYlVLOUNlMHJPc0hhSGJ0VU5VbjVPU2J4MjAvVXU2ZmZxaXd3cFdWZjUxaTZEdm4ydDdlSjV5cQowRkZQTDFLOWtuMGYvT2E0RGNTRmtEeDYrcnAzeExKSjRORSsxZ2orM0c0R3Z0L0czWDBaWkhSa1V1TGI5NDNOCjhtWmlFakdLM2hmdWJsUVZMQVN6UlJNY2dPRDdOYmhKaThLVkpJdUVZbjVkRUpKZ01MNzZ0d3Rwa28rZ3VGeHQKK1FmQ1dlTm5ZRWhCcEl6RDV6R2hGUGczZHRXd0JpcS9wQ05zRXdJdWREZlVRbmhzRm1xb3ZyMDNRQXZKQ3I5Qwo1UlNnRHUyNFRjUXdhS0dQR3IwNzBGWU5yN1FXb0pIT3hvU2h4amw2dkpSWHhKRW43VU5sekxYWElWd3dWVzhPCjQrUGQzVUFMdGt5NVJkeXkyN1Myd0x4N3lkRnVjeWJaRitQM21Na2xaS3dCRk14cjhGQUEyV2tpc1FzQ0F3RUEKQVFLQ0FnQnZGRnhGLzVCZ3N1SHFEWjBZS1lKeXF5ZWN5Y253YU1mZmlVU3IrdTBQcjRpeDBOTkpVTUlzNFFkNAplSkNBYU9mRXdad1BERCs2UmRhMXhZYlY0MnNkQ2c0eEtiZTRVYUg1UHEyb2Q5MmtrL2VpZDJIWDBRcUJKOGtDClIrNWdEN29qb2R4TnBkT0hka3M3Y0EweXNUSnFlWnNvOFN4aitmeDFQaXV2R1lZcnNCVXgzZFJISkx4ZUh6WnUKMWo2b1hUTWt3S0dodTdoWXhGM0tvVE5kZS8xbnEvMjhNTVpGYXcrMkx6M2RKNUx2emxPWUNXS0FHMHdPQm1VdAo5REFDMVFHVWcyYVFoZklVenFHYmlLaWVmc2puT1JYT0l5Z2hBdS9mWSs2NWs4bGx5UWVVMGUxaTdUMU9LaUpHCjRmazJBZlA5UmE4bE13bU10Z2Z3K1BzekxuYzFpN1MxekdZYW9iOEE5c0gyY0hYYjZuR0RZL0NTTTBjb3RFTkwKdXMySjhja0NwbE55TVNyQVFqYVk3NGpscDRPTWpHb3FZTEVZeFp6L1VqdytJRVJEcW13bURZeVBRUFZnQjdzZQpndkMraTVvYnR5akpmaG13ajlBYjQ4VkpPQUIyVUEvRlEzaldkTmxwMGtybkxsOHY5cmxyWTVTdE5tMFdDeEZBCnJOc3cxN1NYTjQ0SGF4L2t6M04ybkdFOWJseHJ5bXVkZ2Y0Zmo4RmJoalZTSWtVU0d3L3Fqd241bXFpSERJcGsKMDZob0g5WmIrQWpjSlZHUlBzWDg3bmFTOUxvRE91ZnpiRXZ4RzZ2UE5KTk1EK1JGc1RKbFJ4QkwyRmg0VGNEeQo2OUtxQlpQZGJ1cTdyRS9zL2MxanRQSEFCZ09ETEZGYUJCcDd4Vm9jK1RkRlBtLzg0UUtDQVFFQS9QUzJSdjhNCmVkOW1xNXBvNlJjQ0NsaHRUR2lpaHMxQzJPK1oyb1FNSWhzR21wakliRysxOE9nMjBMWitzUXhqSFd2UWZENVUKY0hxb0tmYjEwalRidEwrVXpjaTZRVjhSTDRQYXJWaUFtTVJ3c09TUFpuY2JoWnluSmhsSVhtSUt1VnNHMXlxMApZdW1ZN0I1Z3NteDc3RDVSNFdxUlFEaGdRUUtLT1lTekNZME13eEUvbFJHRTVQT0tvV2VMMUcxdGxIc0p0TUhDCldnYnVDNlc2Tnd3b09ZMGtWeFgrZDRiNFFsT0F6Zy9YeXFkTGhtUmVxMXF5ck56LzVsNUZ5SE5hZEtMMUxoZmUKeXk3YUhzbU9OeXc5cGI1T004MTVJM0VIUzhzamdXWU9iVG10dVgxbU1zdDVhRnB0MEFSSEZISjd5eG1FY2FqYgplYmVKbVFzT1E1cS9xUUtDQVFFQTY1dFl1TFF4RXhvUmZ4aHdnSU1KZFFFQllRcXI1ckVMLytNb205cFZlSUJlCjZqYjdKNjhLbG9SNTcrZG5DTko3c2x3R2I1bnZpN0QybXFRb0Y1ejBzYVFSdUZIZm9oM2RZdTdQc1NEK1ArOSsKdC9YTjVtTEVRd3lYOEF4ZFNLVkZWbVMzc2VOR3pkeWNhU0dGRFFNeGFON1drTUc5dHd4aTZqS1NVY1c0MmxOMwpjK2ZoNHlFWlcxZU9RTEl2QVdzTjFlZ2pydkNnbHFKL3NkYW90R25tR0FCYVJrY2dQa2NpSDBwRHEwWVVUT3dBCnJPZDlFK0tRc3I1MzZZeGI1bis3YzRublc4YVhURmZKMWVwQ1BBNnNVMDJUc0IzcGFYWjVkVkIvMDg5WWNVWisKeTIycGlCSXZNTmt4MzFlQVRkQVB2MkZ3OFFsSng2RURKeDNqZHJOcmt3S0NBUUJMaWZ5QStSdE5yY1FvVE1VMQpqbFJpcUlPRFJOLzhKNEhsN0s5aVRQcWVtTG1CSTB6KzdPRkZYdU0zc3Jma3dWRTc4UDFpak82RVpHeWhrNGxYClM4ZXNrMldwaWw3c3RLb2FLV0w5VHllZjkxRzcwWlZ0UVBac0VScnRTckdNMWZSajQrWUlEVTJ2R0JrOXNkaW8KajdMMkdxb3pDYkwwbmFGSTZLeEVmdmRFUytYYXZ1VGc3RWxtWWNBdGNSR1Z6MVBnK2xrc3JJd1FmRzlMOVNMRgoyNUNMbHpXWitBeDB2MDZWNS8vWUNXMGtySTdtUkVUdElQbW9tNXFqdmRWVEJmZW1TeCt5c3hncVR3UitHeXlvCkYwTVZvdDRScERPZnZOb3o3U2JlTm83cVdVWWkxV3JXa21MZ0lka1hQSi9KWUdMTmhRSkRPdXpIeldKKzNJbFcKOFBoNUFvSUJBSEFmR1hXc3FyNEFaZHNwOGovMkhBWUdXSFdwOG14eVROZVZicm5jaVZnekh2Z3UrZzdFaWpGZgpFZmhORXdkcncxbjUyVVk2NTNoKzJweDFDbTlTVGxCTFYvTnpZdzF2VU8vSDNpYlpJS1drZjVWajhIeDIvQmM4Cll3SGxvRzcxMTYxcGVORzY2dk1FelpwcVRUc0lEZmR1TklYbTdUV3pPMDlnaWFsSWd0UERiTkZIeElPbU9MN3oKUjhzYUFLeVlHWmwyUTZUNDlqTTVXYk4wQ0F6emFJQjdpbnB2VnJUTWZUeU94dTAzQ0dvaTFaOXkrbDhBTHdRaApDRWVvZUFPVlBjdWFFUFBuNmhCMnBxS2FQTEwvK0pvY0RQQi9DNWtZdkd4THhza3huMUVvenlaWUpabVByYzE5ClR2S09YWXlxT3hSRWRzNytNSkpEMlpBLzlRT0VGdWtDZ2dFQkFNSVlTZVlZdXhMUzRiY0pYcWxuc1RLUmpwTG4KTG1mR1dwZ25RcFJDMlRQZXJMRnp5U3VEMVc5R2xpUXFyNnA3clkvYTBnZnRTNHU1Zi82WjE3QUozZENzbllEbApRUU1IaDdQOFM1U2RFYUhZeTZzUVlXQmFpUDZDb2JXaFI1akdUMVlZeEhGTlQreW9QSUtjWUZaeTQrMkpQMGo3Ck9sS2dEY1pwWDFvd3dBTnNyd1dNSmV2T2JreTdqWDlpVWhIeVhzOWlFTUliZFBlcSs1SnpNYUUvNGdUdUpWeFMKcU1Lc1hHWDNabU9qdkxJMFZlTi9UM000K29zUjArRUFHQmR6Q3M2U3VFMXFKcHFQWWRzNC9jWUxHb1JDZkdLdQpaZkFrL2s0c1BNd0tHbXlHUHNMNnFSb0YyRU9nZ2RncVkvQWNQNzkvSWJPNmEvNnFHSTJUYXFhOHlEbz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
        token: yJnmXguRe0N4sXyPudnSxcyPSMIUKbFA

  docker_client_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEAymxJY18HLsD7Jlc7rSNfcHufv08+0ysF3M4NPrOGjkVyU1hI
    7BOND/i3lzpq1okNqVnvijoQZsHGR1q2A3jnG3z8SjcUA+exgyHFFpJgMXMiijg4
    YMaeLIS01OVSeOJQogI391MT8QGjYUahHDwg+9XyJgdRW83pQ6LZvH5cFezoBXK2
    L3/oGa7vhAq6/YVzibC/widaYmaLACvJXsD5cdHJ86GLOd7YxXOWPi4WL7AjKT1C
    8sk6Co7NQrzTK7wotPfTu4hmSWZTnaxIyIm0iVtTNSfeZq3U65b2UdCcf5Dja9Su
    PMW5zHYLDdbKd2qvTeuoagN7zpHV35n/HGNICLp8l6cg2qCiswntAsGYK1TYjG+L
    qQFPuXz+SplKXU5aaV1J8HZRNYMAV/IpuHza23LwsfzKI78E66jO6fTQ7kxlEwdG
    f6dQUdqwt8IzUp4YeCkCyp042d9a5oE+/Z6unTXS2PbTVVaxDayaRxg5tJNoC2Ro
    vNhVRFdpGeZaCK4bdHtfAXv+wg+bOnbOzrgpf131UiUgvrCgO34nBjPEQnK4e4xY
    oet+y1fB0D9pNQtV1v7OzwSEMr9IUI7iTzt44DZZinP/vMAuKQ+8O5aoI0NtzGD8
    capbg/Cl3XCjJC86Ei6lXMHbtP/tiNx4lE3B2xW1SlN/gh9AQlDSCFvpqcMCAwEA
    AQKCAgAS7KLDzouOXG5efENRAYCXtIcPzKnT9i67IOxuEzyeKnHwxs0yfPVwK9GG
    Kuj4G6ISVh0l8B2+bZlK7Hkdw/zfPgUcLyAI6W1YFB0n6hFiLiBpia4Dpi39fX6m
    dLYMJSRisRBoZ/TyUDPlEURYrmprAOp9kauSiKKpNx1iGPIk/pwGfl33/N5HIGq2
    DobC0uolUkfrL+CsWGfgYTeXSzVG5dUamNy6UVI0y4SdVZOva6kt3tNWfWeWuxkH
    hz261gF8QbsiyjK94/onQIchcHZXbRlPW+XX9aJ1UAzBQ16OMo6Ac0bC2b1wFw0b
    gxw0o921zDVXi/HUMyAqomwOTF3cgHSV4E41j3mLx6bX1cFDfAw6n5JVVA2kbYfa
    T14IEAtZvGP7S9PS0cTUiMBhULjorQcO7j/9kTHDemkgtlt46vMd3+hj0oRC7OtM
    7cgaEftGEx7z8aEELWsDgzEydEOx+hUDIJF9ERPaowg4XGPk25XClwxAyVKWhlV6
    MQ0JBRIvduwoYyeteO4p35/gxYtjio7qQRDNOO78mvXravgiUBCn9lL61Aebw4Np
    pDPyMxxsXOo9L6PVjn4RviCWa94IAhVWaqhh6cB8B+7G4Qwec+P+O7jS/xnnRsCO
    KwZtLyGX0UbxWqAKLIfGL4WX75lxXHvwlMqUbBx6LRV+d9B0MQKCAQEA6x3nMm4u
    loFxYmAei9vU6AgaxiQyYzrMa4HdAYQsAMSQOtyJWhfMEmS1W4Wa5D5vsYlmG41L
    g5FJPPcwnwHOZfOw6bVIBc6eZyZMiQ9+sll+6+DGezbtm14sYvg+ZPKGIzHBMhNT
    5bBDPO+onIkkwRxUV6AV6GIH95ifh0YuxtdwvYMIPCnTsiwOJkDGBj2i7WIYJZdy
    LxjWjOSKtfgFWWCQImzZ1MICijWzKfVOGzYIdpTjtPJV5aaHDImVQkuMlSfTwdRC
    W1MrepARs1GqFv4Plvc4hOp3GVOSvDRG3eXKpM16un2VAzJJv7jmiz5vcbEaJkZY
    aUaGl+gO7PnHyQKCAQEA3Gb9dxNyBGa60JinWZStHDpq5r4KV+43Ls4z4eG1inHi
    AM3u07odtKTl6stN+cmHdbSDBQGwR9ji97RUSQ7KD85Qe3uV2pPmSvXuVSH+3pyr
    AYInijbTzgciOyj4ksQ6Q0Oor9/7/G8Q7XqYRh06JdWhikM02P77qCOvtI36Um27
    lEKJQoDME/8JpOxyAq4FDeh4YUNCfUIjeMeLCf7+Co3Gmrmi8aiHUzOSDGc5qhzn
    a5SKbDtIF3GPgdTWs1cH1PKvYl/EAjuO97QBczxsDbU3WTSzHKE1l9x4GQ/NFTa9
    1FniC/0yzqXS96fCmeKaJbzc9SUOhgN/kv1L5g/DKwKCAQEAjInVVrmxs1kwc0NN
    PwBqZT/i8SlVzSaqZmC7wFpHCzZzmBuXJnkvDJeSKGDWUzRXA2JD3Jg62SwRARYo
    xAMKYrqlty0bHg2BddrYyNywON9yFIDJY4FTyhkiow4MDb9CGut0tgADmDoiFtyS
    hu8bPys15yLTtZJTfNaIFQ4Ii+bfhwg59exyk//tfUQemkBhkU+fa2j5YdmQ9aru
    lxLn76LexRUXqCtH5WFv9Nail3VW3brl2ZU5bwp5ky7yPyx1nfqugx/jgj9Wr+5K
    Bkv8Rb4bh3vDFwAnrMXd4g3FhoIC/Tut7qd+WOjIWIenlvf9GZJpNRO7aUI01bxq
    n5A2sQKCAQEAmVHzxJ/8Ut972Zw33nM0sUxaDUXqQBzwulirctjmxvZN961KFHOG
    MqH7ZwgiqD7vQoxeEF+KV5Ci4xnJAEGPgstM5XmlVzZHn6HRN9u8RvPJafU2uElH
    siz4PRtVQBPNS/mHIUG5M3O33NvJjgzK5ILmKx5xZvqJ6f9ZPUr+9dRsBsj6Xw7l
    6IskFFx/Oyn/ThuHknGNkUEvF9gH+t4trv3NSNkWZvGLoe9gC8zLKnGM8yOT35Kl
    pdlTsUd0S7GhOxvPsalY2wy/ecT4tUc1C5wicqXca3AhrhCqYxTA358DEvOr8hci
    /uoQBkPnddFS1im5s7chkUxhtMkLwXD5nQKCAQEAha0aZ56w23mt/oU4TwzfjRJM
    PDa4yb91etAJBO/D7PqOSw5IInEF6Ty0d2JdGd1qivDpGem9ULi3yn4orB1RqGAG
    s/BVGlcXGrv8l3qyFIKLrJ8QeOfZz2TZlbrSP2S+FO/jPalSXMmGwfyS01Mm/J39
    tl8iqgsfS5mBxqsV8yJE4dqdoP62vU6IBwQuChsBgWJeAgSrepXu7TS9PebtgrLl
    76FWVEOITjHMC0BqQQr4+Cp7KW943jVQgcOnI+p5oTPDCI+uicoSr2lbPS9pmW6z
    l1xY1Qbb3Y7BJoGkGZU859zyhcdhILw/Tfql1zrbO73TAX3GcgXNBDSlhXRU0g==
    -----END RSA PRIVATE KEY-----
  docker_client_cert: |
    -----BEGIN CERTIFICATE-----
    MIIFxDCCA6ygAwIBAgIJAJiMFDFWOWIFMA0GCSqGSIb3DQEBCwUAMIGUMQswCQYD
    VQQGEwJDTjELMAkGA1UECAwCU0gxCzAJBgNVBAcMAlNIMQwwCgYDVQQKDANTQVAx
    DDAKBgNVBAsMA0NTQzERMA8GA1UEAwwIQ0RERVZPUFMxPDA6BgkqhkiG9w0BCQEW
    LURMXzU3QkE2ODgwNUY5OUI3MTBGNjAwMDAxQUBleGNoYW5nZS5zYXAuY29ycDAe
    Fw0xNzA3MTcwNzE3MjhaFw0yNzA3MTUwNzE3MjhaMC0xKzApBgNVBAMMImNucHZn
    bDU2NTg4NDE3LnB2Zy5nbG9iYWwuY29ycC5zYXAwggIiMA0GCSqGSIb3DQEBAQUA
    A4ICDwAwggIKAoICAQDKbEljXwcuwPsmVzutI19we5+/Tz7TKwXczg0+s4aORXJT
    WEjsE40P+LeXOmrWiQ2pWe+KOhBmwcZHWrYDeOcbfPxKNxQD57GDIcUWkmAxcyKK
    ODhgxp4shLTU5VJ44lCiAjf3UxPxAaNhRqEcPCD71fImB1FbzelDotm8flwV7OgF
    crYvf+gZru+ECrr9hXOJsL/CJ1piZosAK8lewPlx0cnzoYs53tjFc5Y+LhYvsCMp
    PULyyToKjs1CvNMrvCi099O7iGZJZlOdrEjIibSJW1M1J95mrdTrlvZR0Jx/kONr
    1K48xbnMdgsN1sp3aq9N66hqA3vOkdXfmf8cY0gIunyXpyDaoKKzCe0CwZgrVNiM
    b4upAU+5fP5KmUpdTlppXUnwdlE1gwBX8im4fNrbcvCx/MojvwTrqM7p9NDuTGUT
    B0Z/p1BR2rC3wjNSnhh4KQLKnTjZ31rmgT79nq6dNdLY9tNVVrENrJpHGDm0k2gL
    ZGi82FVEV2kZ5loIrht0e18Be/7CD5s6ds7OuCl/XfVSJSC+sKA7ficGM8RCcrh7
    jFih637LV8HQP2k1C1XW/s7PBIQyv0hQjuJPO3jgNlmKc/+8wC4pD7w7lqgjQ23M
    YPxxqluD8KXdcKMkLzoSLqVcwdu0/+2I3HiUTcHbFbVKU3+CH0BCUNIIW+mpwwID
    AQABo38wfTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIF4DBjBgNVHREEXDBahwQKOonz
    hwQKOon0hwR/AAABgiJjbnB2Z2w1NjU4ODQxOC5wdmcuZ2xvYmFsLmNvcnAuc2Fw
    giJjbnB2Z2w1NjU4ODQxNy5wdmcuZ2xvYmFsLmNvcnAuc2FwMA0GCSqGSIb3DQEB
    CwUAA4ICAQDXHJYGBGxY0DUwPB5f9mEw/R97eK/wTaP8C03F8IuU5odBHCLv9SRV
    RwJ6euifbGRNwrgnfrMpYmYhzJC5fUpVf07rEWHWAMOLZoZxlZ54DFNCi8RZuYZt
    cLJsLwy3vi9qDmW5vMVvGH7Al296cAtq3qwla8F9w/OQJhV1MOntFnQhMftMxjh/
    RmGK+7U/+6M9XNx9BuoKvx0aiDVovz5/g117wk19EO6qmgEr7c9rTmNN6bpaJzUr
    pg8XCG4DfrBaXFSSo6lNIJPnq0UbIA/99eIdQUIC3gvBo9BJdx4pbfiZXDlcIWaF
    k9LsjwzohdrBn0ws2AEtIqOgdMSv/tQ+2TQTBpDohsygOzezEP93zX5VWrApGmAH
    lQAop4xyrhD5S4bHqq1y3KLIA53A1u8NFvk/ay+/m5TKLMQFf1auQ9yjtdv76iXl
    iLeueC7ORhLUc9uXf7Ku5pucANhhZPcrET9DUIvCtqf1ASJKZyXEazIZP2nAJnWg
    u80oGOGpr7Ds9Aj/V+0fNY3IYnZtZWTI/phFqsZ8u/BZXSLhme2z85bTALIk/pSS
    MXwnvLnk8n89djcvroitsD7nfJjx1JyQLFikuzhjPmchFZ+jtUZSf13fZAbXs4hm
    ZennP1hG1+JfSKGzktGBiFKG00tG1YHwUsLyuPBOM81y2XtVvFKAqw==
    -----END CERTIFICATE-----
  docker_ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIIFpjCCA44CCQDKyHYdS2F35TANBgkqhkiG9w0BAQsFADCBlDELMAkGA1UEBhMC
    Q04xCzAJBgNVBAgMAlNIMQswCQYDVQQHDAJTSDEMMAoGA1UECgwDU0FQMQwwCgYD
    VQQLDANDU0MxETAPBgNVBAMMCENEREVWT1BTMTwwOgYJKoZIhvcNAQkBFi1ETF81
    N0JBNjg4MDVGOTlCNzEwRjYwMDAwMUFAZXhjaGFuZ2Uuc2FwLmNvcnAwHhcNMTcw
    NzE3MDcwNjAyWhcNNDQxMjAyMDcwNjAyWjCBlDELMAkGA1UEBhMCQ04xCzAJBgNV
    BAgMAlNIMQswCQYDVQQHDAJTSDEMMAoGA1UECgwDU0FQMQwwCgYDVQQLDANDU0Mx
    ETAPBgNVBAMMCENEREVWT1BTMTwwOgYJKoZIhvcNAQkBFi1ETF81N0JBNjg4MDVG
    OTlCNzEwRjYwMDAwMUFAZXhjaGFuZ2Uuc2FwLmNvcnAwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDpuVcmgmM+L2AiW1hNDDoRS4ks2uZl3YC6BevdgvQe
    GewCNkhhI6wPJaw6dkGZjldmLG7fQOdzLf2sPiKu7Vxk2j1op+d4csG+byn43Wad
    HPdLM49rY54XxLrIkOVr0ucQTEEbAd2Ekr0XpT1vdbK7AmgD/FO3xtR9uilWEZ9T
    FiKKMT8l71doAOqKCZ5Q7+CSA0v9YQiNTshrqPTvRBAiNObELXNN3rNL7LN1bnFN
    2Z6ptCU/Yxx8piA4hV2SP/EXiD+iKoyHK6Xztps/t8LhxIAae19swkhMIl0Ue+uU
    6HhUm2nD7oD7a9PQWahkJpLFqaR1f+P23nhZRcNOVN1eZrllVcxVSQ78L3eRqt8p
    Xm6dV636DGs2xOhYMYoorkCo0XENO9tYh1KU98m7BkV/pCUSm7V0PjislUp3KWZ6
    U7OevmOJ880fciayrncK3Smfgr5dDRq4Te6HYHux7nH8kLrV0SBwb1w08Q0SRyRg
    PQaTx22+yghDufuMJ+HB/XQBOVUSGcdEX4l1sdo2mu6mstZHlS5AJdzSEnjOMAI6
    eJAnqAvVygD2KIRihIS3gZMZl7TcQ+V/hhAJI7aHIW0RddZbNd3OPWy9kaLGpVmz
    rtS3518FIQuHNoYo2nVsom12PrkuYcsxj6V5xfsjZnHaNy/Kq9QoOl4i2PZ9XaT0
    0wIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQB06G4w2hNyHbh/OCP5Nb0MvNkBdnvk
    q1ltARd4DOcNDzhSfj5k/Kvzo2WenqZOdsu/RopqadfgCYYXF5OHF1VtwZiN3dCg
    bCXsyikJUONvEvA2aasV6i4YXsFtw+3MePr03WNJr1+AebJ6jd/LBnwoNPNKnbY/
    adDkaEBzaAEEAP+hktLldRX/onpm1FF1bapmMT2vlyLCMQCqS5WD3wZCnAruZzdO
    HQjRm0sZNzhiWzZZvqlpgffQL83uTZTukHUOnUpLUv7ln3dTxxoPFxcjhsJFo1Dg
    KDxOG+/QwaQt6h43eXYhQJsH4aYXtj7x/PDZSus/pyuKbtijRQ7JEof4HXzZSP7D
    Nqb+3hfFy9UPXQm/ATeaxmChnghN+APMRzWpKzX0lQAGGLeLwVCtpn4K0mBOGOYb
    cOKMs0mpdgz4J8fTgAo5lA1wCXzZHxzR2NgbDwNAAvh6MOpVIkUZKUplDRhZpkZg
    e6FGIkjYZYWnIB7LQfJPiGhICNCxuWcfGoV4maUbnkVEqxFMSWAOnl1AXCZdAiFq
    slGsx7miXO/KCgYpT9qu6uChQWCdZQ6+vxRK0K9As02kmrvFAt0BLhSQFW3hgZDG
    2C9Ymnezh1zAy86Jdnh84i3+5/86GbDshEeI+va7G0A5eu/H9i38du5Gri5tbfyA
    95hpoh5HRCC4/w==
    -----END CERTIFICATE-----

  supervisord.conf: |
    [unix_http_server]
    file=/var/run/supervisord.sock

    [supervisord]
    nodaemon = true
    logfile=/var/log/supervisord.log ; (main log file;default $CWD/supervisord.log)
    pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
    childlogdir=/var/log/supervisor         ; ('AUTO' child log dir, default $TEMP)
    logfile_backups=0
    loglevel =debug
    user=root

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [supervisorctl]
    serverurl = unix:///var/run/supervisord.sock

    [program:chown]
    priority=20
    command=chown -R jenkins:jenkins /var/jenkins_home
    startsecs=0
    
    [program:downloadci]
    priority=25
    environment=JENKINS_HOME=%(ENV_JENKINS_HOME)s
    command=/usr/local/bin/download-ci-connect-plugin.sh
    startsecs=0
    user=jenkins
    [program:jenkins]
    priority=30
    environment=JENKINS_HOME=%(ENV_JENKINS_HOME)s
    command=/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java  %(ENV_JAVA_OPTS)s -jar /usr/share/jenkins/jenkins.war 
    redirect_stderr=true
    redirect_stdout=true
    #stdout_logfile=/dev/stdout
    user=jenkins
    startsecs=200
    stopsignal=0

    [program:sshd]
    priority=30
    command=/usr/sbin/sshd -D
    redirect_stderr=true
    redirect_stdout=true
    stopsignal=0
    #stdout_logfile=/dev/stdout
    user=root
  
