---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-slave-jdk7
  namespace: jenkins
  annotations:
spec: 
  type: NodePort
  selector: 
    name: jenkins-slave-jdk7
  ports: 
    - name: ssh-port
      port: 22
      nodePort: 32002
      targetPort: 22
      protocol: TCP  