kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: owl
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi 