---
apiVersion: v1
kind: Service
metadata:
  namespace: jnc
  name: redis-jnc-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis-master
      targetPort: 6379
      nodePort: 30279
  selector:
    name: redis

