apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: jnc
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
      annotations:
        prometheus.io/port: '9121'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'         
    spec:
      containers:
      - name: jnc-redis
        image: registry.gcsc.sap.corp/redis/redis:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: 2048Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c  
              - /usr/local/bin/redis-cli shutdown
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master/
          name: redis-config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-jnc-redis
        - name: redis-config
          configMap:
            name: redis-jnc-configmap 
