apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
      annotations:
        prometheus.io/port: '9121'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'         
    spec:
      containers:
      - name: redis-master
        image: gcr.io/google_containers/redis:v1
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c  
              - /usr/local/bin/redis-cli shutdown
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      - name: redis-commander
        image: rediscommander/redis-commander
        env:
        - name: REDIS_HOSTS
          value: instance1:localhost:6379
        ports:
        - name: redis-commander
          containerPort: 8081
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - name: http 
          containerPort: 9121
          protocol: TCP

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-redis

