---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-master
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis-master
      targetPort: 6379
      nodePort: 30379
  selector:
    name: redis

---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-commander
spec:
  type: NodePort
  ports:
    - port: 8081
      name: redis-commander
      targetPort: 8081
      #nodePort: 30381
  selector:
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-exporter
  annotations:
    prometheus.io/port: '9121'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/metrics'
spec:
  type: NodePort
  ports:
    - port: 9121
      name: redis-exporter
      targetPort: 9121
     # nodePort: 30021
  selector:
    name: redis

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis-ingress 
  namespace: redis
spec:
  rules:
  - host: redis.gcsc.sap.corp
    http:
      paths:
      - path: /
        backend:
          serviceName: redis-commander
          servicePort: 8081

