kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: git-history-pvc
  namespace: git
  annotations:
    volume.beta.kubernetes.io/storage-class: "devops-k8s-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
