kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: owl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cscdevops-nfs
  resources:
    requests:
      storage: 10Gi 
