apiVersion: v1
kind: Service
metadata:
 name: mongo
 namespace: owl
 labels:
   name: mongo
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   role: mongo
---
apiVersion: v1
kind: Service
metadata:
 name: mongo-ui
 namespace: owl
 labels:
   name: mongo-ui
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 8081
 - port: 9104
   targetPort: 9104
   protocal: TCP
 selector:
   role: mongo