apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: owl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
      annotations:
        prometheus.io/port: '9001'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'  
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: owl-mongo
      initContainers:
      - name: mongo-init
        image: registry.gcsc.sap.corp/mongodb/mongo:3.4
        command:
        - /bin/bash 
        - /root/create-user.sh
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db        
        - name: create-user-shell
          mountPath: /root/create-user.sh
          subPath: create-user.sh                   
      containers:
        - name: mongo
          image: registry.gcsc.sap.corp/mongodb/mongo:3.4
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - --auth
            - --smallfiles
            - --noprealloc
            - --storageEngine=wiredTiger
            - --wiredTigerIndexPrefixCompression=0
            - --wiredTigerCollectionBlockCompressor=none
            - --wiredTigerCacheSizeGB=0.5
            - -vvvvvv
          ports:
          - containerPort: 27017
          lifecycle:
            preStop:
              exec:
                command: 
                  - /bin/bash 
                  - -c 
                  - /usr/bin/mongod --shutdown
            #      - mongo --eval "db.getSiblingDB('admin').adminCommand({shutdown:1,timeoutSecs:5})
            #      - mongo --eval "db.getSiblingDB('admin').shutdownServer({timeoutSecs:10})"                    
          securityContext:
            capabilities:
              add:
              - SYS_RESOURCE            
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            limits:
              memory: 2Gi
        - name: mongo-exporter
          image: registry.gcsc.sap.corp/mongodb/mongodb_exporter:latest
          imagePullPolicy: IfNotPresent
          args:
          - -mongodb.uri
          - "mongodb://admin:admin@localhost:27017"
          - -v
          - "10"
          resources:
            limits:
              memory: 100Mi     
          ports:
          - name: mon-port
            containerPort: 9001
            protocol: TCP        
        - name: mongo-express
          image: registry.gcsc.sap.corp/mongodb/mongo-express:0.40
          imagePullPolicy: IfNotPresent
          env:
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "true"
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
            value: admin
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            value: admin
          - name: ME_CONFIG_MONGODB_SERVER
            value: localhost
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: admin
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: devops
          ports:
          - name: web-port
            containerPort: 8081
            protocol: TCP        
          resources:
            limits:
              memory: 100Mi                    
      volumes:   
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc     
      - name: create-user-shell
        configMap:
          name: owl-mongo-cm
          items:     
          - key: create-user.sh
            path: create-user.sh   
                  