apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: owl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
      annotations:
        prometheus.io/port: '9104'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'  
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: owl-mongo
      containers:
        - name: mongo
          image: registry.gcsc.sap.corp/mongodb/mongo:3.4
          imagePullPolicy: IfNotPresent
          command:
            - mongod
            - --smallfiles
            - --noprealloc
            - --storageEngine=wiredTiger
            - --wiredTigerIndexPrefixCompression=0
            - --wiredTigerCollectionBlockCompressor=none
            - --wiredTigerCacheSizeGB=0.5
            - -vvvvvv
          ports:
          - containerPort: 27017
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c 
                  - sleep 60;
                  - user_count=$(/usr/bin/mongo --quiet --eval "db.getSiblingDB('admin').system.users.find({user:'db'}).count()");
                  - if  [[ $user_count -ne 1 ]] ; then
                  - /usr/bin/mongo --eval "db.getSiblingDB('dashboard').createUser({user:'db',pwd:'dbpass',roles:[{role:'readWrite',db:'dashboard'}]})"; fi
            preStop:
              exec:
                command: 
                  - /bin/bash 
                  - -c 
                  - /usr/bin/mongod --shutdown
            #      - mongo --eval "db.getSiblingDB('admin').adminCommand({shutdown:1,timeoutSecs:5})
            #      - mongo --eval "db.getSiblingDB('admin').shutdownServer({timeoutSecs:10})"                    
          securityContext:
            capabilities:
              add:
              - SYS_RESOURCE            
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            limits:
              memory: 2Gi
        - name: mongo-sidecar
          image: registry.gcsc.sap.corp/mongodb/mongo-k8s-sidecar:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=prod"
        - name: mongodb-exporter
          image: registry.gcsc.sap.corp/mongodb/mongodb_exporter:latest
          imagePullPolicy: IfNotPresent
          args:
          - -mongodb.uri 
          - mongodb://localhost:27017
          resources:
            limits:
              memory: 50Mi     
          ports:
          - name: mon-port
            containerPort: 9104
            protocol: TCP        
        - name: mongo-express
          image: registry.gcsc.sap.corp/mongodb/mongo-express:0.40
          imagePullPolicy: IfNotPresent
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: localhost
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: admin
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: devops
          ports:
          - name: web-port
            containerPort: 8081
            protocol: TCP              
      volumes:   
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc             