kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
spec:
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      hostNetwork: true
      containers:
      - name: nfs-provisioner
        image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
        ports:
          - name: nfs
            containerPort: 2049
            hostPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
          - name: rpcbind-udp
            containerPort: 111
            protocol: UDP
        securityContext:
          capabilities:
            add:
              - DAC_READ_SEARCH
              - SYS_RESOURCE
        args:
          - "-provisioner=cscdevops-nfs"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP      
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - name: export-volume
            mountPath: /export
          - name: localtime
            mountPath: /etc/localtime                
      volumes:
      - name: export-volume
        hostPath:
          path: /data/nfs-provisioner
      - name: localtime
        hostPath:
          path: /etc/localtime  