apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: haproxy-apiserver-proxy
  labels:
    app: haproxy-apiserver-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: haproxy-apiserver-proxy
      annotations:
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - image:  haproxy
        name: haproxy-apiserver-proxy
        command: ["haproxy","-f","/usr/local/etc/haproxy/haproxy.cfg"]
        resources:
          limits:
            memory: "1024Mi"
            cpu: 1024m
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
          - name: haproxy-conf
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: haproxy-conf
          configMap:
            name: haproxy-apiserver-proxy-conf
            items:
            - key: haproxy.cfg
              path: haproxy.cfg