apiVersion: v1
kind: Pod
metadata:
  name: nginx-apiserver-proxy
spec:
  hostNetwork: true
  containers:
  - image:  haproxy
    name: haproxy-apiserver-proxy
    command: ["haproxy","-f","/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
    - containerPort: 8443
      hostPort: 8443
      name: https    
    volumeMounts:
      - name: localtime
        mountPath: /etc/localtime
      - name: haproxy-conf
        mountPath: /usr/local/etc/haproxy/haproxy.cfg
  volumes:
    - name: localtime
      hostPath:
        path: /etc/localtime
    - name: haproxy-conf
      hostPath:
        path: haproxy.cfg