apiVersion: v1
kind: Pod
metadata:
  name: nginx-apiserver-proxy
spec:
  hostNetwork: true
  containers:
  - image:  nginx:stable
    name: nginx-apiserver
    ports:
    - containerPort: 6443
      hostPort: 6443
      name: https
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: nginx-conf
    hostPath:
      path: /etc/nginx/nginx.conf              