apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'mail.lmy.com:25'
      smtp_from: 'admin@lmy.com'
      smtp_require_tls: false
      # the slack Incoming WebHooks url
      slack_api_url: 'https://hooks.slack.com/services/xxxx'  

      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
      wechat_api_secret: 'xxxx'   #application secret created for the receving the alert
      wechat_api_corp_id: 'xxxx'  # corp ID 
    # The root route on which each incoming alert enters.
    route:
      # The root route must not have any matchers as it is the entry point for
      # all alerts. It needs to have a receiver configured so alerts that do not
      # match any of the sub-routes are sent to someone.
      receiver: 'default-slack-receiver'
      # The labels by which incoming alerts are grouped together. For example,
      # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
      # be batched into a single group.
      group_by: ['alertname', 'instance']
      # When a new group of alerts is created by an incoming alert, wait at
      # least 'group_wait' to send the initial notification.
      # This way ensures that you get multiple alerts for the same group that start
      # firing shortly after another are batched together on the first
      # notification.
      group_wait: 30s
      # When the first notification was sent, wait 'group_interval' to send a batch
      # of new alerts that started firing for that group.
      group_interval: 5m
      # If an alert has successfully been sent, wait 'repeat_interval' to
      # resend them.
      repeat_interval: 3h
      # All the above attributes are inherited by all child routes and can
      # overwritten on each.
      # All alerts with job=ems
      # are dispatched to the ems-email-receiver pager.
      routes:
    #  - receiver: 'ems-email-receiver'
    #    match:
    #       job: ems
    receivers:
    - name: 'default-email-receiver'
      email_configs:
      - send_resolved: true
        to:  'mail@lmy.com'
        headers:
          From: DL_57BA68805F99B710F600001A@exchange.sap.corp
          Subject: 'Alert: {{ template "email.default.subject" . }}'
    - name: 'default-slack-receiver'
      slack_configs:
      - send_resolved: true
        channel: '#monitoring'
        title: "{{ .Status | toUpper }}: {{ .CommonAnnotations.summary }}\n"
        text: "{{range .Alerts }}\nDescription: {{ .Annotations.description }}\n{{ range .Labels.SortedPairs }} {{ .Name }}: {{ .Value }}\n{{end}}Metrics:    <{{ .GeneratorURL}}| Click here>\n{{ end }}"
    - name: "default-wechat-reciever"
      wechat_configs:
      - send_resolved: true
        to_user: "" # send to the IDs of the users,refer to https://work.weixin.qq.com/api/doc#10167
        to_party: "" #send to department ID of the contact,  refer to https://work.weixin.qq.com/api/doc#10167, here we create a new department which     includes some users.
        to_tag: ""  # send to the IDs of the tags,refer to https://work.weixin.qq.com/api/doc#10167
        agent_id: "1000002" # the application agentID, you need to use existing or create new application in wechat
        corp_id: "wxd6c3b48a11938c18" # corp ID
