apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      # Prometheus server
      - name: prometheus
        image: prom/prometheus:master
        args:
          - '-storage.local.engine=none'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://alertmanager:9093'
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus
        resources:
          limits:
            cpu: 1200m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 400Mi
      - name: remote-storage-adapter
        image: apsm/remote_storage_adapter
        args:
        - /bin/sh
        - -c
        - /usr/bin/remote_storage_adapter
          '-influxdb-url=http://monitoring-influxdb.monitoring.svc:8086'
          '-influxdb.database=prometheus'
          '-influxdb.retention-policy=autogen'
      volumes:
      - name: config-volume-prometheus
        configMap:		
          name: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 9090
      name: prometheus
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus

