kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ngrinder-monitor-pvc
  namespace: ngrinder
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cscdevops-nfs
  resources:
    requests:
      storage: 10Gi 
