apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ui-config
  namespace: registry
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "devops"
  REGISTRY_URL: http://registry:5000
  CONFIG_PATH: /etc/ui/app.conf
  HARBOR_REG_URL: "registry.gcsc.sap.corp"
  HARBOR_ADMIN_PASSWORD: "DevOPS2017"
  HARBOR_URL: http://ui
  AUTH_MODE: "db_auth"
  LDAP_URL: "ldaps://ldap.mydomain.com"
  LDAP_SEARCH_DN: ""
  LDAP_SEARCH_PWD: ""
  LDAP_BASE_DN: "ou=people,dc=mydomain,dc=com"
  LDAP_FILTER: ""
  LDAP_UID: "uid"
  LDAP_SCOPE: "3"
  LOG_LEVEL: debug
  UI_SECRET: "1fBAUV92ULx0iuuo"
  SECRET_KEY: "CCUZvY5lJEa1Sw9T"
  JOBSERVICE_SECRET: "NnK3769h0thS3Nk2"
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "https://registry.gcsc.sap.corp"
  TOKEN_URL: http://ui
  SELF_REGISTRATION: "on"
  USE_COMPRESSED_JS: ""
  VERIFY_REMOTE_CERT: "off"
  TOKEN_EXPIRATION: "30"
  EXT_REG_URL: "registry.gcsc.sap.corp"
  config: |
    appname = ui
    runmode = dev
    [lang]
    types = en-US|zh-CN
    names = en-US|zh-CN
    [dev]
    httpport = 80
    [mail]
    host = mail.sap.corp
    port = 25
    from = admin <jennings.liu@sap.com>
    ssl = false
  pkey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEA5VRdugo1pcgrlFoGQaMTQ9rpD+YcvKbefknA3U9ky6kbhUq7
    q+l3ofCTR65pnV+CBoyXEr4R7jOg/kS6Qh0AzF74NLFsKSIuqk4LC0OpjpMuoJog
    Bcm31ChYueojSTFy3JCSmSeSs47eG9G6onJpItQZoPkhPx321mdJxFi0PiDY7B+i
    g3rz9+11QDbOPmM5YWIeJecTSXaoRHX5QTACasSgr05uv3kYqWRVU47AcOv2abKH
    mL5dxkyP+jOFOcKCPTxCrkPrW3nbxzsKNodf8JMsO5fDywufzgAVc4wXhHOHW6FC
    6ovxRSbxaVk6hYQ2++/tQBCjwzWQzbOIN6Pbwb+/k4IEIQIUCC/5JfU2ZWKb/1tp
    bFJCQefqLQQp9A+hl6FujL8XenlgzI6ensrZt3/Aclk4IXkUcpzT/Dkna3htBPbk
    p6Ni/nYgQnkWERQf00WY68+aFFabFT+UtI8hOGWNd8isCnAHoGYpJtqACOxUYPlt
    EKyLvzxSW0qaJ9BClnmHTv24edF9+X3ej5FHedCYhHPgMKk+GPb4afXPPeTYKL7e
    hzC90Y9NspanlkgXA3MNv2gD2SfjxKr5ulYbqvs9UyQhm+U1C4/j0OZNR2ZoqDRo
    ysLNZhBokVDUxNpCSPHBtFDcobkK98cppy2yHUk79XToI/Z3bex89nPmt1UCAwEA
    AQKCAgBUUjX4LsLVBwnHDWbZgX2W6InjV6ffUbfjVXj9prCYFcDRvM3OgxSCzbNJ
    mv6oZ7Kmd9EgihSLsh4S//BAWOuvOYgnz8jGQxRHeFSlOqbAjquJT8JQfoACGSeu
    jEGXKwBhyyKr/5n4PaK7Nd1a15iCvtwBjTjFPV5CLU45TKhRY8B+6Y7Wq0HDOmNv
    Tfd9hvxVKz+Mji9QRrnOGlagumdZHJ08eClOa9c+iW66P3XQz2IWMRecePp/7CzQ
    QVtOBo/etiaKbty+EMtXsQSrUhFborGT49SQ9uA2XV+F0c/f2p69eUjidrwqwgvn
    wXA8IYYaEnj4omWkZDCvAcEnPC+TlnmxCdlNqJorEPC7xZXTIR8XMS7ubp4fugfW
    gMn/IpuZR73y8xFBgQwEyJj4Eb5PRskcyu0hK8fxItwAQS8MeN3ibUJGCqxAHfhX
    xuxo+GEmUxXDbnkH2pWVlBoWsjOtlpx0HmO3avba3UMBprQgBqGknoKpQ2avLsfm
    MGFs39zXBQjHClisJvCCi+fF2BMHVxvNxbBGLQRBLNx1O5JuHhoKQxDLjUEg73Tw
    8KMIZB6Opf2xawyBBJoJ7t887z6WODSuhVXhQGuv9KMQ882+aAzoMeVQY1mDMbum
    uJ70nUC+d5ijAqy0nvZt48pYdA+V89QU5V3GCnbP/HeO1HFfbQKCAQEA/G3hKzf2
    NbpD9PcnQp4zb2b/7vCAm6zudKiaqn/ikNtKldzdwzlsf+ayp06qT7sg5Y/Ji3HP
    AsW2mQq8Df60HwRi8FJlM1GOkjyiYYaPXe8K7515HHELAOuWaqrG5Al6JM00vjaD
    DUM5niPMYtSuOSfXq7jOmFg20OU3sglEkf7iZo+CAx9BF9VmUQYT1Fu1H9NgvilJ
    Hmrs7JRDmIsP7Fki8TQ9b6HXDwx7iyv29SlrVu0sRBVKTMJqM2z3DL0Wvh0VUZpJ
    VTtDnOfpSOcbNRaLtqB7Wej7tC8hNS6Mme4zjP5cilJlgG1WscqeVgDM1kBVQw0C
    YEIL87Y72JztTwKCAQEA6JLV/I5SMSk68Fti0qlFPkhXGTPGZZe74TzT7ILFn+8h
    DzB4FItM39jS+87hVwxDHAIGlDzGkd/7ob0AEtv+y3Ne0YUE59uxoKLVe+vDp8iT
    2iauXu4y42FTBdQ3M+P52VbVuW8Ev8vZvU2NnPi9i7Bn8YIotXLlsOeWpeGwZR5U
    lCeYl4vBiq8Xu9D/DIPqvkV0Q6sSMYcizq3bNjTaUw0ZvjUBljmFZmiVFHiKitSp
    qkIsW8gZc7fizWCMhtqjVlkEgdZNvyVNbtBfgUgFLzwz2uInmy+gLW2w882ZchCg
    OIvGOiaB1NOWtl8QVq16nD6/2USpujFR1NSW+X9QGwKCAQEAvMG1dEnedAKaulzu
    IKSHtbABhTyWDtLbZKSHMyN52fQA69tCgK858NIjmXP7aq91Q/OnM/ygXWRWzE34
    nUZujhsLmMUkI6HCyJtKmT6zifwr402PuLLXFZMU4SJeozpq+YXxAKNmj85LEXOX
    a/e5Z8fhP+lrowOjycT9RsYjXkCIL0T0ZT1DwXyzi7bNsSf6Ypf/aXMZ2AMAs0+S
    1Eh4WbW1qUP1BLqyQ/CDmWgAvQaB23hyd16sNoXSQC4k9oOWtAavYFvMpk0wm+3W
    xcr6z1HSm3eZhXvwa6YqYMg0Hw69wZqavFwsxkH8Z+opSApFIZjtqLvboPsCUPVd
    /vYphQKCAQEAxE8c3F7tNZ3NqBAbLCHA1r+M9TLkpeAbsBT99Ma1NThNOVr6IK0s
    KE4GWJHZVvZ8tulm0D00hvD+nxi/NSwIt4YcZNHYwDSKjEKl3EG3FqqRUjQQPwTk
    Y1VFFMh6CAzIWhGXuTviUFoq4kTR4ct7gqtWMV5iKjZfdqEkYcRMdi3RynRZsqE+
    rmb4q4nPnqrCu/Q4HN4LL08XrEjHncui9TM7pXdsbXcECNsB6xOMLX8v7wyIELin
    8ysl/6EdPL7T3BCrY0SWv18nKwArfR5jcelpA7qdH7plg7LxB/llKgiqlNA2c+MI
    97HZpvo6+k7YDYZRvXzdntH+dp0zCknSPQKCAQEAwMCELor3PVREnuXQm4tZmAmD
    wVyI0dUS5ZwCDTIL3DgaD8DiXrHWLPvcOFd8vVrdn+USj7rlCpuyGXi4NvA0lm+e
    3m+bc+Q2GP5vdiDR86+FME9wu7H/f1yD31nKzVFw8deaWwhLpCwAQz8DEI4gPnhP
    sBiTP6x0LqQqzWcSdNE0xQwKj7gmuJR4WRWg6W+iAEr7Dlckqvvy0mDpsRfCH3dO
    Hc8PeyjqfDUKiDBd3cv6XMfCBAS4jAvxuTeXY6KOQvcIspiAe7WHCfTeKBF9RoCW
    k0XRL/43y/lImUua6BGG2V5L/rhUvnAIh6LYqJ1cN2xbQBjcarJIRolsO7Flog==
    -----END RSA PRIVATE KEY-----



