kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sp1-hana122-pvc
  namespace: sportsone
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
