---
apiVersion: v1
kind: Namespace
metadata: 
  name: jenkins
  labels: 
    name: jenkins
---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins
  namespace: jenkins
  annotations:
spec: 
  type: LoadBalancer
  selector: 
    name: jenkins
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: slave-port
      port: 50000
      targetPort: 50000
      protocol: TCP      
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata: 
  name: jenkins
  namespace: jenkins
  labels: 
    name: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  template: 
    metadata: 
      name: jenkins
      labels: 
        name: jenkins
    spec: 
      terminationGracePeriodSeconds: 10
      containers: 
      - name: jenkins
        image: jenkins/jenkins:lts
        ports: 
          - containerPort: 8080
          - containerPort: 50000
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 500Mi
        env:
          - name: JAVA_OPTS
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85"
          - name: JENKINS_OPTS
            value: "-hudson.model.UpdateCenter.never=true -Djenkins.install.runSetupWizard=false"
        volumeMounts: 
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: localtime
            mountPath: /etc/localtime
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
      securityContext:
        fsGroup: 1000
      volumes: 
      - name: localtime
        hostPath:
          path: /etc/localtime
  volumeClaimTemplates:
  - metadata:
      name: jenkins-home
      # annotations:
      #   volume.beta.kubernetes.io/storage-class: anything
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi




---
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: jenkins
   namespace: jenkins
   annotations:
     kubernetes.io/ingress.class: nginx
     ingress.kubernetes.io/ssl-redirect: true
 spec:
   rules:
   - host: jenkins.gcsc.sap.corp
     http:
       paths:
       - path: /
         backend:
           serviceName: jenkins
           servicePort: 80


