 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: jenkins-master
   namespace: jenkins
   annotations:
     kubernetes.io/ingress.class: nginx
     #ingress.kubernetes.io/ssl-passthrough: "true"
 spec:
   tls:
   - hosts:
     - jenkins.gcsc.sap.corp
     secretName: jenkins-tls
   rules:
   - host: jenkins.gcsc.sap.corp
     http:
       paths:
       - path: /
         backend:
           serviceName: jenkins-master
           servicePort: 8080