kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-pvc
  namespace: jenkins
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 
