apiVersion: v1
kind: Service
metadata: 
  name: jenkins-master
  namespace: jenkins
  annotations:
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/prometheus'  
spec: 
  type: ClusterIP
  selector: 
    name: jenkins-master
  ports: 
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: slave-port
      port: 50000
      targetPort: 50000
      protocol: TCP    
---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-exporter
  namespace: jenkins
  annotations:
    prometheus.io/port: '9103'
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/metrics'
spec: 
  type: ClusterIP
  selector: 
    name: jenkins-master
  ports: 
    - name: http
      port: 9103
      targetPort: 9103
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-master-ssh
  namespace: jenkins
spec: 
  type: NodePort
  selector: 
    name: jenkins-master
  ports: 
    - name: ssh-port
      port: 22
      nodePort: 32001
      targetPort: 22
      protocol: TCP
