apiVersion: v1
kind: Service
metadata: 
  name: jenkins-master
  namespace: jenkins
  annotations:
spec: 
  type: ClusterIP
  selector: 
    name: jenkins-master
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: slave-port
      port: 50000
      targetPort: 50000
      protocol: TCP    


---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-master-ssh
  namespace: jenkins
spec: 
  type: NodePort
  selector: 
    name: jenkins-master
  ports: 
    - name: ssh-port
      port: 22
      nodePort: 32001
      targetPort: 22
      protocol: TCP
