apiVersion: v1
kind: Pod
metadata:
  name: etcd-server
spec:
  hostNetwork: true
  containers:
  - image: quay.io/coreos/etcd:v3.3.2
    imagePullPolicy: Always
    name: etcd-container
    args:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd   --name=kube-master2 --data-dir=/var/lib/etcd
      --client-cert-auth=true 
      --trusted-ca-file=/var/lib/etcd/certs/EtcdCA.pem
      --cert-file=/var/lib/etcd/certs/etcd-server.pem
      --key-file=/var/lib/etcd/certs/etcd-server-key.pem
      --advertise-client-urls https://192.168.59.202:2379
      --listen-client-urls https://192.168.59.202:2379
      --peer-client-cert-auth=true 
      --peer-trusted-ca-file=/var/lib/etcd/certs/EtcdCA.pem 
      --peer-cert-file=/var/lib/etcd/certs/etcd-peer.pem
      --peer-key-file=/var/lib/etcd/certs/etcd-peer-key.pem
      --initial-advertise-peer-urls=https://192.168.59.202:2380
      --listen-peer-urls=https://192.168.59.202:2380
      --initial-cluster-token=etcd-cluster
      --debug
    ports:
    - containerPort: 2380
      hostPort: 2380
      name: peerport
    - containerPort: 2379
      hostPort: 2379
      name: clientport
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: datadir
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    - mountPath: /usr/share/ssl
      name: usrsharessl
      readOnly: true
    - mountPath: /var/ssl
      name: varssl
      readOnly: true
    - mountPath: /usr/ssl
      name: usrssl
      readOnly: true
    - mountPath: /usr/lib/ssl
      name: usrlibssl
      readOnly: true
    - mountPath: /usr/local/openssl
      name: usrlocalopenssl
      readOnly: true
    - mountPath: /etc/openssl
      name: etcopenssl
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etcpkitls
      readOnly: true
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/kubernetes/certs
      name: etcdcert
    - name: localtime
      mountPath: /etc/localtime         
  volumes:
  - hostPath:
      path: /var/lib/etcd
    name: datadir
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /usr/share/ssl
    name: usrsharessl
  - hostPath:
      path: /var/ssl
    name: varssl
  - hostPath:
      path: /usr/ssl
    name: usrssl
  - hostPath:
      path: /usr/lib/ssl
    name: usrlibssl
  - hostPath:
      path: /usr/local/openssl
    name: usrlocalopenssl
  - hostPath:
      path: /etc/openssl
    name: etcopenssl
  - hostPath:
      path: /etc/pki/tls
    name: etcpkitls
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /var/lib/kubernetes/certs
    name: etcdcert
  - name: localtime
    hostPath:
      path: /etc/localtime   