kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cscdevops-nfs
            - name: NFS_SERVER
              value: 10.97.157.125
            - name: NFS_PATH
              value: /k8s_store
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.97.157.125
            path: /k8s_store
