apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminserver-deployment
  namespace: registry
  labels:
    name: adminserver-deployment
spec:
  replicas: 1
  selector:
    name: adminserver-apps
  template:
    metadata:
      labels:
        name: adminserver-apps
    spec:
      containers:
      - name: adminserver-app
        image: harbor/adminserver
        imagePullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: LOG_LEVEL
          - name: EXT_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EXT_ENDPOINT
          - name: AUTH_MODE
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: AUTH_MODE
          - name: SELF_REGISTRATION
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: SELF_REGISTRATION
          - name: DATABASE_TYPE
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: DATABASE_TYPE
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MYSQL_PORT
          - name: MYSQL_USR
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MYSQL_USR
          - name: MYSQL_PWD
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MYSQL_PWD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MYSQL_DATABASE
          - name: REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: REGISTRY_URL
          - name: TOKEN_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: TOKEN_SERVICE_URL
          - name: EMAIL_HOST
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_HOST
          - name: EMAIL_PORT
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_PORT
          - name: EMAIL_USR
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_USR
          - name: EMAIL_PWD
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_PWD
          - name: EMAIL_SSL
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_SSL
          - name: EMAIL_FROM
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_FROM
          - name: EMAIL_IDENTITY
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: EMAIL_IDENTITY
          - name: HARBOR_ADMIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: HARBOR_ADMIN_PASSWORD
          - name: PROJECT_CREATION_RESTRICTION
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: PROJECT_CREATION_RESTRICTION
          - name: VERIFY_REMOTE_CERT
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: VERIFY_REMOTE_CERT
          - name: MAX_JOB_WORKERS
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: MAX_JOB_WORKERS
          - name: UI_SECRET
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: JOBSERVICE_SECRET
          - name: TOKEN_EXPIRATION
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: TOKEN_EXPIRATION
          - name: CFG_EXPIRATION
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: CFG_EXPIRATION
          - name: GODEBUG
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: GODEBUG
          - name: ADMIRAL_URL
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: ADMIRAL_URL
          - name: WITH_NOTARY
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: WITH_NOTARY
          - name: RESET
            valueFrom:
              configMapKeyRef:
                name: harbor-adminserver-config
                key: RESET
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-key
          mountPath: /etc/adminserver
        - name: config
          mountPath: /etc/adminserver/config
      volumes:
      - name: secret-key
        configMap:
          name: harbor-adminserver-config
          items:
          - key: secret-key
            path: key
      - name: config
        configMap:
          name: harbor-adminserver-config
          items:
          - key: config
            path: config.json