 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ngrinder-controller
   namespace: ngrinder
   annotations:
     kubernetes.io/ingress.class: nginx
     #ingress.kubernetes.io/ssl-passthrough: "true"
 spec:
   tls:
   - hosts:
     - ngrinder.gcsc.sap.corp
     secretName: ngrinder-secret
   rules:
   - host: ngrinder.gcsc.sap.corp
     http:
       paths:
       - path: /
         backend:
           serviceName: ngrinder-controller
           servicePort: 80