kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ngrinder-controller-pvc
  namespace: ngrinder
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cscdevops-nfs
  resources:
    requests:
      storage: 50Gi 
