# Setup docker-build as a reader. This has to be a
# ClusterRoleBinding to get access to non-resource URLs
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-read
subjects:
  - kind: ServiceAccount
    name: docker-build
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-reader

