groups:
- name: cluster rules
  rules:
  - alert: High CPU usage 
    expr: ((sum(node_cpu{mode=~"^(?:user|nice|system|irq|softirq|steal|idle|iowait)$"}) BY (instance, job)) - (sum(node_cpu{mode=~"^(?:idle|iowait)$"}) BY (instance, job))) / (sum(node_cpu{mode=~"^(?:user|nice|system|irq|softirq|steal|idle|iowait)$"}) BY (instance, job)) * 100 > 95
    for: 10m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): has really high CPU usage for over 10m'
      summary: 'High CPU Usage detected!'
  - alert: High node Load Average 
    expr: ((node_load5 / count(node_cpu{mode="system"}) WITHOUT (cpu, mode)) > 1)
    for: 2m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): Average Load is high'
      summary: 'High Average Load detected'
  - alert: Node Swap Usage is high
    expr: (((node_memory_SwapTotal - node_memory_SwapFree) / node_memory_SwapTotal) * 100) > 75
    for: 2m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): Swap usage usage is above 75% (current value
        is: {{ $value }})'
      summary: 'High Swap usage detected'
  - alert: Node Memory Usage is high
    expr: (((node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) / (node_memory_MemTotal) * 100)) > 75
    for: 2m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): Memory usage is above 75% (current value is: {{ $value }})'
      summary: 'High memory usage detected'

  - alert: Node Low Data Disk
    expr: ((node_filesystem_size{mountpoint="/data"} - node_filesystem_free{mountpoint="/data"})  / node_filesystem_size{mountpoint="/data"} * 100) > 75
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): data disk usage is above 75% (current value is: {{ $value }})'
      summary: 'Low data disk space detected'
  - alert: Node Low /Var Disk
    expr: ((node_filesystem_size{mountpoint="/var"} - node_filesystem_free{mountpoint="/var"})  / node_filesystem_size{mountpoint="/var"} * 100) > 75
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): var disk usage is above 75% (current value is: {{ $value }})'
      summary: 'Low var disk space detected'      
  - alert: Node Low Root(/) Disk
    expr: ((node_filesystem_size{mountpoint="/"} - node_filesystem_free{mountpoint="/"})/ node_filesystem_size{mountpoint="/"}* 100) > 75
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{$labels.node}}({{$labels.instance}}): root disk usage is above 75% (current value is: {{ $value }})'
      summary: 'Low root disk space detected'



  - alert: Deployment Generation Mismatch
    expr: kube_deployment_status_observed_generation{job="kubernetes-service-endpoints"} != kube_deployment_status_observed_generation{job="kubernetes-service-endpoints"}
    for: 5m
    labels:
      severity: page
    annotations:
      description: Deployment of {{$labels.namespace}}/{{$labels.deployment}} failed - observed generation != intended generation.
      summary: 'Deployment  Generation Mismatch detected'

  - alert: Deployment Replicas Mismatch
    expr:  (kube_deployment_spec_replicas{job="kubernetes-service-endpoints"} != kube_deployment_status_replicas_available{job="kubernetes-service-endpoints"})      or (kube_deployment_spec_replicas{job="kubernetes-service-endpoints"}  unless    kube_deployment_status_replicas_available{job="kubernetes-service-endpoints"})
    for: 5m
    labels:
      severity: page
    annotations:
      description: Deployment of {{$labels.namespace}}/{{$labels.deployment}} failed - observed replicas != intended replicas.
      summary: Deployment Replicas Mismatch detected
  
  - alert: Pod Restarting Too Much
    expr: rate(kube_pod_container_status_restarts[1m]) > 1 / (5 * 60)
    for: 1h
    labels:
      severity: page
    annotations:
      description: Pod {{$labels.namespace}}/{{$labels.pod}} restarting too much.
      summary: Pod restarting too much detected.

  - alert: Instance is Down
    expr: up == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for  more than 5 minutes.'
      summary: Instance down 
  - alert: Kube-Apiserver is Down
    expr: kube_pod_container_status_ready{container="kube-apiserver"} == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: kube-apiserver in pod {{$labels.pod}} is down.
      summary: kube-apiserver is down
  - alert: Kube-Controller-Manager is Down
    expr: kube_pod_container_status_ready{container="kube-controller-manager"} ==
      0
    for: 5m
    labels:
      severity: page
    annotations:
      description: kube-controller-manager in pod {{$labels.pod}} is down.
      summary: kube-controller-manager is down
  - alert: Kube-Scheduler is Down
    expr: kube_pod_container_status_ready{container="kube-scheduler"} == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: kube-scheduler in pod {{$labels.pod}} is down.
      summary: kube-scheduler is down
  - alert: etcd is Down
    expr: kube_pod_container_status_ready{container="etcd-container"} == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: etcd-container in pod {{$labels.pod}} is down.
      summary: etcd-container  is down

  - alert: POD memory usage high
    expr: 100 * container_memory_working_set_bytes{image!="",name=~"^k8s_.*"} / container_spec_memory_limit_bytes{image!="",name=~"^k8s_.*"} > 80  and  container_spec_memory_limit_bytes {image!="",name=~"^k8s_.*"} !=0
    for: 5m
    labels:
      severity: page
    annotations:
      description: "POD {{$labels.namespace}}/{{$labels.pod_name}}  usage  is above 80% of its limits(current value is: {{$value}}) !"
      summary:  "POD  usage  is above 80% of its limits !"

- name: Jenkins rules
  rules:
  - alert: Jenkins JVM  memory high
    expr: 100 * vm_memory_total_used / vm_memory_total_max  >80
    for: 5m
    labels:
      severity: page
    annotations:
      description: "Jenkins  {{$labels.instance}}  JVM  memory usage  is above 80%(current value is: {{$value}}) ! "
      summary:  "Jenkins  JVM  memory usage  is above 80% !"
  - alert: jenkins slave node is offline 
    expr: jenkins_node_offline_value >1
    for: 5m
    labels:
      severity: page
    annotations:
      description: "Jenkins  {{$labels.instance}}   has more than 1 slave node down(current value is: {{$value}}) !"
      summary:  "Jenkins  has more than 1 slave node down  !"  
  - alert: jenkins  is not healthy
    expr: jenkins_health_check_score !=1 
    for: 5m
    labels:
      severity: page
    annotations:
      description: "Jenkins  {{$labels.instance}}  is not healthy!"
      summary:  "Jenkins   is not healthy  !"
  - alert: jenkins  CPU usage is high
    expr: vm_cpu_load > 0.8
    for: 5m
    labels:
      severity: page
    annotations:
      description: "Jenkins  {{$labels.instance}}   CPU load is high(current value is: {{$value}}) !"
      summary: "Jenkins  CPU load is high !"

- name: nginx controller rules
  rules:
  - alert: too much unexpected  ingress response
    expr: irate(nginx_upstream_responses_total{kubernetes_pod_name!='',status_code !="2xx"} [5m]) >10
    for: 5m
    labels:
      severity: page
    annotations:
      description: "the unexpected  ingress response(response code: {{$labels.status_code}}) for upstream {{$labels.upstream}}:{{$labels.server}} is increased,current irate is {{$value}} !"
      summary: "the unexpected  ingress response is increased !"


- name: kube-dns rules
  rules:
  - alert: The rate of DNS  error is increasing
    expr: irate(skydns_skydns_dns_error_count_total[5m]) !=0
    for: 5m
    labels:
      severity: page
    annotations:
      description: "The {{$labels.cause}} error is increasing in {{$labels.k8s_app}}  for system {{$labels.system}}, current irate is {{$value}}"
      summary: "The DNS error is increasing "


- name: etcd rules
  rules:
  - alert:  Etcd is down 
    expr: etcd_server_has_leader !=1 
    for: 2m
    labels:
      severity: page
    annotations:
      description: "etcd is down "
      summary: "etcd is down"
  


- name: tomcat rules
  rules:
  - alert: The conext of tomcat is not running 
    expr: tomcat_context_state_started !=1 
    for: 2m
    labels:
      severity: page
    annotations:
      description: "The tomcat conext {{labels.context}} is not running on instance {{labels.instance}}:{{label:kubernetes_pod_name}}  "
      summary: "The tomcat conext is not running !"


