apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  namespace: jnc
  labels:
    name: mysql-rc
spec:
  replicas: 1
  selector:
    name: mysql-apps
  template:
    metadata:
      labels:
        name: mysql-apps
    spec:
      containers:
      - name: mysql-app
        image: vmware/harbor-db:v1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "1"
            memory: 4096Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
              configMapKeyRef: 
               name: jnc-mysql-config
               key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: localtime
          mountPath: /etc/localtime            
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: jnc-msyql-pvc 
      - name: localtime
        hostPath:
          path: /etc/localtime
