---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-master
spec:
  type: NodePort
  ports:
    - port: 6379
      name: redis-master
      targetPort: 6379
      nodePort: 30379
  selector:
    name: redis

---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis-commander
spec:
  type: NodePort
  ports:
    - port: 8081
      name: redis-commander
      targetPort: 8081
      #nodePort: 30381
  selector:
    name: redis

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redis-ingress 
  namespace: redis
spec:
  rules:
  - host: redis.gcsc.sap.corp
    http:
      paths:
      - path: /
        backend:
          serviceName: redis-commander
          servicePort: 8081

