apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
    - get
    - watch
    - list
- nonResourceURLs:
  - '*'
  verbs:
    - get
    - watch
    - list