apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - proxy
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - watch
  - list
  - proxy