kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-nodejs-2-workspace
  namespace: jenkins
  annotations:
#    volume.beta.kubernetes.io/storage-class: "devops-k8s-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-nodejs-2-maven
  namespace: jenkins
  annotations:
#    volume.beta.kubernetes.io/storage-class: "devops-k8s-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
