apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: gcr.io/google_containers/kube-scheduler:v1.7.0
    imagePullPolicy: Always
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-scheduler --kubeconfig=/srv/kubernetes/kube-scheduler.kubeconfig
      --v=5 --leader-elect=true 
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /var/log/
      name: logfile
    - mountPath: /srv/kubernetes/
      name: certs
      readonly: true
    - name: localtime
      mountPath: /etc/localtime         
  volumes:
  - hostPath:
      path: /var/log/
    name: logfile
  - hostPath:
      path: /srv/kubernetes/
    name: certs
  - name: localtime
    hostPath:
      path: /etc/localtime  