kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-data-pvc
  namespace: monitoring
  annotations:
#    volume.beta.kubernetes.io/storage-class: "devops-k8s-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
