 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: tomcat
   namespace: tomcat
   annotations:
     kubernetes.io/ingress.class: nginx
 spec:
   rules:
   - host: tomcat.gcsc.lmy.corp
     http:
       paths:
       - path: /
         backend:
           serviceName: tomcat
           servicePort: 8080