---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.5.0-beta.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes
        - --sink=influxdb:http://10.58.137.244:8086
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 100Mi          
        volumeMounts: 
        - name: localtime
          mountPath: /etc/localtime  
      - name: eventer
        image: gcr.io/google_containers/heapster-amd64:v1.5.0-beta.0
        imagePullPolicy: IfNotPresent
        command:
        - /eventer
        - --source=kubernetes
        - --sink=influxdb:http://10.58.137.244:8086?withfields=true
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 100Mi          
        volumeMounts: 
        - name: localtime
          mountPath: /etc/localtime  
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime