apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: jnc
  name: jnc-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jnc-redis
  template:
    metadata:
      labels:
        name: jnc-redis
      annotations:
        prometheus.io/port: '9121'
        prometheus.io/scrape: 'true'
        prometheus.io/scheme: 'http'
        prometheus.io/path: '/metrics'         
    spec:
      containers:
      - name: jnc-redis
        image: redis:4.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
            memory: 4096Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c  
              - /usr/local/bin/redis-cli shutdown
        command: ["/usr/local/bin/redis-server"]
        args: ["/usr/local/etc/redis.conf"]
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /usr/local/etc
          name: redis-config
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: jnc-redis-pvc
        - name: redis-config
          configMap:
            name: jnc-redis-configmap 
