apiVersion: v1
kind: Service
metadata:
 name: mongo
 namespace: mongo
 labels:
   name: mongo
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   role: mongo
---
apiVersion: v1
kind: Service
metadata:
 name: mongo-ui
 namespace: mongo
 labels:
   name: mongo-ui
spec:
 type: LoadBalancer
 ports:
 - name: web-port
   port: 80
   targetPort: 8081
 - name: mon-port
   port: 9001
   targetPort: 9001
 selector:
   role: mongo