 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: mongo-ui
   namespace: mongo
   annotations:
     kubernetes.io/ingress.class: nginx
     #ingress.kubernetes.io/ssl-passthrough: "true"
 spec:
   rules:
   - host: mongo-ui.gcsc.sap.corp
     http:
       paths:
       - path: /
         backend:
           serviceName: mongo-ui
           servicePort: 80