apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mail
  name: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mail-pod
        image: mo-b166c2b61.mo.sap.corp/email/email-service:1.0.0
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
